Cargo.toml
src/httpd.rs
src/lib.rs
src/log.rs
src/netif.rs
src/nvs.rs
src/nvs_storage.rs
src/ping.rs
src/private/edge_config.rs
src/private/mod.rs
src/private/net.rs
src/private/stubs.rs
src/start.rs
src/sysloop.rs
src/wifi.rs

- Disambiguate calls to `log` crate with `::log` due to compile issue
- Format with `cargo +nightly fmt`

Unambiguous log

---

src/httpd.rs

The httpd module of `esp-idf` already adds the `Content-Length` header (see [here](https://github.com/espressif/esp-idf/blob/master/components/esp_http_server/src/httpd_txrx.c#L238)) using the buffer length. There is no need to add the header on the Rust side, also makes Postman complain 😆

Fix duplicate `Content-Length` header

---

src/log.rs
src/netif.rs
src/nvs.rs
src/ota.rs
src/ping.rs
src/sysloop.rs
src/wifi.rs

When using this crate with the latest nightly, I was getting an error about the ambiguous `log` uses. It didn't know whether to refer to the crate's `log` module, or the `log` dependency.
This PR fixes that.

Fix ambiguous log use statement

---

src/log.rs

function or associated item not found in `esp_idf_sys::log`

An error occurred when sdkconfig set CONFIG_LOG_DEFAULT_LEVEL_NONE=y 

---

src/http.rs
src/http/client.rs

Currently [embedded-svc](https://github.com/esp-rs/embedded-svc/blob/master/src/http.rs#L6) disables the `http::server` module is std isn't enabled.
Until it supports `no-std`, it should be disabled here as well.

Disable http server if std not available.

---

src/http/client.rs

I noticed that sending data using the http client was broken. The root cause is the error handling in `do_write`. `esp_http_client_write` returns the number of bytes written, but the `esp!` macro converts every non-zero return code into an error.
In `do_read`, the implementation is correct already. I used the error handling from `do_read` in `do_write` now, which should be correct. I already tried the changes and they seem to work fine.

fix sending data in HttpClient

---

Cargo.toml
src/http/client.rs

Use the `uncased` crate when HTTP client is enabled to ensure this.
Fixes #39 in my brief test of my project, tested on an ESP32-C3.

HTTP header keys are case-insensitive

---

src/http/client.rs
src/mqtt/client.rs

Excited to test out the mqtt client, but found this error when using esp-idf v4.4.

Use fully qualified path for c_void in crt_bundle_attach

---

src/mqtt/client.rs

Thanks for all your work on esp-rs! This trivial PR adds MQTT username / password support.
With this change, the [Ably Realtime](https://ably.com/pub-sub-messaging) cloud service seems to work well, using the [recommended configuration](https://ably.com/documentation/mqtt):
- `mqtts://mqtt.ably.io:8883`
- username and password from the API key
- `MqttProtocolVersion::V3_1_1`
- keepalive interval between 15 and 60 seconds

MQTT username/password

---

src/espnow.rs
src/lib.rs

this PR adds support for [ESP-NOW](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_now.html) to the project.
I had to use a hack visible in `new()` that turns off the radio sleep `esp!(unsafe { esp_wifi_set_ps(0) })?;` - otherwise data stops being sent after a few seconds (this seems to be a known [bug](https://github.com/espressif/esp-idf/issues/7496)).
There is a related PR for `esp-idf-sys` and an issue this relates to: https://github.com/esp-rs/esp-idf-sys/pull/78 and https://github.com/esp-rs/esp-idf-sys/issues/70

add esp-now support: safe api for EspNow and callback handling

---

src/espnow.rs
src/lib.rs

The recent addition of ESPNow had references to `std` and `Box` that weren't hidden behind cfg flags. This PR changes `std` to `core` and also add the `alloc` and network checks to `lib.rs`.

Fix espnow.rs to build under no-std

---

src/espnow.rs
src/sntp.rs

Seems to be a leftover from https://github.com/esp-rs/esp-idf-svc/pull/5.
Otherwise it may conflict with the one imported from esp_idf_sys.
```
error[E0659]: `log` is ambiguous
--> /esp-idf-svc-0.39.1/src/sntp.rs:4:5
|
4 | use log::*;
|     ^^^ ambiguous name
|
= note: ambiguous because of multiple potential import sources
= note: `log` could refer to a crate passed with `--extern`
= help: use `::log` to refer to this crate unambiguously
note: `log` could also refer to the struct imported here
--> /esp-idf-svc-0.39.1/src/sntp.rs:8:5
|
8 | use esp_idf_sys::*;
|     ^^^^^^^^^^^^^^
= help: use `self::log` to refer to this struct unambiguously
For more information about this error, try `rustc --explain E0659`.
```

Fix ambiguous `log` import

---

src/http/client.rs

This adds support for `buffer_size_tx` config option in HTTP Client as discussed [here](https://github.com/ivmarkov/rust-esp32-std-demo/issues/79#issuecomment-1116457365)

Add support for buffer_size_tx config option in HTTP Client

---

src/mqtt/client.rs

MQTT messages with null (zero length) payload crash the ESP32 with a guru meditation error when accessing the data. The solution just bypasses this access when `event_data_length` is zero, returning a zero-length Cow.

Fix crash with zero-length MQTT messages

---

Cargo.toml
src/lib.rs
src/ws.rs
src/ws/client.rs

following the esp_websocket_client found here[^1][^2], this commit
wraps the mentioned C library in Rust to expose a safe WebSocket
interface.
The exposed API copies the previously implemented MQTT API. On creating
a `EspWebSocketClientConfig` and passing it to a `EspWebSocketClient`,
the user can call `send` to send data. Manual sending of fragmented data,
Ping/Pong, or Connect/Disconnect are not supported due to the underlying
C library not supporting this, either.
Receiving is done in a new thread with the returned
`EspWebSocketConnection` and its blocking `next` function call, which
wakes on receiving one of the events defined in `WebSocketEventType`.
The `EspWebSocketClient` takes a `time::Duration` timeout since the
underlying C lib requires this but the defined interface in the …

Websocket implementation

---

src/eth.rs

Add possibility to access the ethernet handle after initializing the driver. I needed this because I had to set a phy register.

add with_handle

---

src/http/server.rs

This PR closes the raw socket as part of finishing processing a HTTP request. The callback close_fd() needs also to close the raw socket which was missed in the original implementation and resulted in a socket leak

fixed issue #94

---

src/log.rs

As noted in TODO, use esp_log_level_get to decide whether to log, then use println!() to directly write message, including no-alloc write of record.args().

log: implementation with no allocations

---

src/ping.rs

The `esp_ping_config_t` struct was [recently updated](https://github.com/espressif/esp-idf/commit/f8a4504bc5d153439bd34f6544aab1244143f421#diff-b60c65a810a67b50afef665dc83cfb0732012e846b5f8daaf5dcfd20c02ae912R70), and the `tos` field is now `int`, not `uint8_t`. The field is convered to a `c_types::c_int` in `bindings.rs`, and so the following error is thrown:
```rust
ryan@ryan-pc:/opt/rust-workspace/projects/esp32s2-workspace/main$ cargo +esp build
Compiling embedded-io v0.3.0
Compiling esp-idf-hal v0.38.0 (https://github.com/esp-rs/esp-idf-hal#7d9bec77)
Compiling esp-idf-svc v0.42.0 (https://github.com/esp-rs/esp-idf-svc#1cad9a87)
Compiling main v0.1.0 (/opt/rust-workspace/projects/esp32s2-workspace/main)
Compiling embedded-svc v0.22.0
error[E0308]: mismatched types
--> …
```

Convert from u8 -> c_int

---

src/espnow.rs

Both functions were missing the `&self` parameter, making them
difficult to use. Additionally, "version" was misspelled.
Just some minor mistakes I noticed while developing with espnow.

peer_exists() and get_vers[i]on() were not usable

---

src/nvs_storage.rs

The 6th byte was replaced by the 7th, the 7th was always 0.

NVS Storage get_raw() was missing a byte if len < 8

---

src/ota.rs

These functions are in fact the same till you change the boot-slot.
Only after that, they differ.
I assume this was an honest mistake, as `get_boot_slot` already calls `esp_ota_get_boot_partition`.

Ota function get_running_slot() retrieves boot-slot, not running-slot.

---

src/ping.rs

It looks like 4ba41cd7c introduced a clippy allowance that should have referenced the lint via underscore, rather than hyphen:
https://rust-lang.github.io/rust-clippy/master/#useless_conversion

[ping] correct clippy lint rule name

---

src/mqtt/client.rs

When I create an MQTT connection, and let the variable go out of scope, I get this error in the logs:
`W (912) MQTT_CLIENT: Client asked to stop, but was not started`
At first that scared me a bit, but I think the problem is that the MQTT client is stopped twice (and the warning is harmless).
https://github.com/esp-rs/esp-idf-svc/blob/1cad9a87d439d715681c323ddb8972a0bc70b6c5/src/mqtt/client.rs#L362-L366
First calls stop, after destroy. However, in the destroy function this happens:
https://github.com/espressif/esp-mqtt/blob/9a56b2f086cb43fe981fc92c80fb926081b180fb/mqtt_client.c#L827-L829
In other words, stop() is called twice, creating the warning in the logs.

Fix double stop() when an MQTT instance goes out of scope

---

src/netif.rs

This PR sets the default mac for any initialized mac (if it can be done reasonably) and allows to set a custom max during creation (or at a later point in time).
That way the `get_mac` method doesn't require an unsafe call to [esp_netif_set_mac](https://esp-rs.github.io/esp-idf-svc/esp_idf_sys/fn.esp_netif_set_mac.html) to initially set the mac address.
This is a breaking change, as it modifies the members of the InterfaceConfiguration struct.
closes #105

#105 Add option to set a mac for an interface and use the default if none is set

---

src/eth.rs
src/wifi.rs

Fixes #106 and allows third parties to test wether or not an IpEvent is related to an EspWifi instance.
This allows using the eventloop to get all wifi events and to filter for relevant events.

Publish method for filtering ip_events from outside

---

src/http/server.rs
src/httpd.rs

Fixes failed build with experimental enabled. Usual bug:
```
error[E0659]: `log` is ambiguous
--> /home/tcb/.cargo/git/checkouts/esp-idf-svc-d824ae6d48aa3d54/3d894c7/src/http/server.rs:14:5
|
14 | use log::{info, warn};
|     ^^^ ambiguous name
|
= note: ambiguous because of multiple potential import sources
= note: `log` could refer to a crate passed with `--extern`
= help: use `::log` to refer to this crate unambiguously
note: `log` could also refer to the struct imported here
--> /home/tcb/.cargo/git/checkouts/esp-idf-svc-d824ae6d48aa3d54/3d894c7/src/http/server.rs:22:5
|
22 | use esp_idf_sys::*;
|     ^^^^^^^^^^^^^^
= help: use `self::log` to refer to this struct unambiguously
```

fix occurrences of 'use log' instead of 'use ::log'

---

src/wifi.rs

ESP-IDF seems to assume that you only call esp_wifi_disconnect
when you called esp_wifi_connect first. Otherwise it will
simply return -1, without explaining further why.
The ESP_ERR_WIFI_NOT_STARTED is only returned when esp_wifi_start()
wasn't called. But ClientStatus cannot be Connected if it hasn't.
As such, that check is no longer required.
Fixes #89, and see there for more discussion about this topic.

Fix: only call esp_wifi_disconnect() when esp_wifi_connect() was called

---

src/wifi.rs

This commit fixes displaying of the received signal strength, as these are signed values (dBs).
This depends on https://github.com/esp-rs/embedded-svc/pull/28.

fix: show signal strength as signed integer

---

src/ota.rs

Fix time formatting in FirmwareInfo

Fix time formatting in FirmwareInfo

---

src/netif.rs

```
error[E0659]: `log` is ambiguous
--> /home/ronen/.cargo/git/checkouts/esp-idf-svc-a28457b0e32c6283/707bd7e/src/netif.rs:638:9
|
638 |     use log::info;
|         ^^^ ambiguous name
|
= note: ambiguous because of multiple potential import sources
= note: `log` could refer to a crate passed with `--extern`
= help: use `::log` to refer to this crate unambiguously
note: `log` could also refer to the struct imported here
--> /home/ronen/.cargo/git/checkouts/esp-idf-svc-a28457b0e32c6283/707bd7e/src/netif.rs:640:9
|
640 |     use esp_idf_sys::*;
|         ^^^^^^^^^^^^^^
= help: use `self::log` to refer to this struct unambiguously
For more information about this error, try `rustc --explain E0659`.
error: could not compile `esp-idf-svc` due to previous error
```

disambiguate crate `log` and `esp_idf_sys::log`

---

src/mqtt/client.rs

this is fixing #146 the issue that a pointer to [] is actually 0x1 (not 0x0).
I fixed not only publish() but also enqueue() as this was also not working (but failed silent for me).
There is a new commit https://github.com/espressif/esp-idf/issues/9719 which fixes the enqueue() function in esp-idf which would cause an actual issue in the rust enqueue() function as well.

Fix #146 by providing std::ptr::null if payload is empty

---

src/netif.rs

The `*mut esp_netif_t` makes `IpEvent` not implement `Send`, so it's either `unsafe impl Send for IpEvent {}` as I've done here, or to wrap the pointer in `RawHandleImpl`, and have it implement `RawHandle` just like `EspNetif`, I'm ok with that too. @ivmarkov, what do you think?

make `IpEvent` `Send`

---

src/ota.rs

This way when using async/await to receive ota data, the future can be `Send`, which some executors expect.

Make EspOtaUpdate Send

---

src/http/server.rs
src/mqtt/client.rs
src/ota.rs
src/timer.rs

- new fields added in `esp-idf/master`, all defaulting to `NULL`
- fix new clippy lints

Fix new clippy lints, added null-by-default fields in `httpd_ssl_config_t`"

---

Cargo.toml
src/http/server.rs

I'm pretty sure using a `static mut` to store types that don't implement `Send` may be unsound.
`EspHttpServer::stop` can be called from any thread, and if we pass a closure that isn't `Send`, and then call stop from another thread, it would be unsound.
Not sure about `httpd` internals, does it promise to only call the handler from the same thread? If not it also has to be `Sync` (which also is a requirement by  the borrow checker anyway.

Get rid of `static mut`, force WS handler to be `Send + Sync`

---

src/wifi.rs

Minor fix.
I think scanning can be implemented without disconnecting and stopping the driver in the future.

cleanup stop and disconnection calls

---

Cargo.toml
src/espnow.rs
src/eventloop.rs
src/http/client.rs
src/http/server.rs
src/mdns.rs
src/mqtt/client.rs
src/napt.rs
src/netif.rs
src/notify.rs
src/nvs.rs
src/ota.rs
src/ping.rs
src/private/net.rs
src/sntp.rs
src/ws/client.rs

- fix `ESP NOW` for `esp-idf` `master` and `v5.1+`
- use `EspError::from_infallible`

Fix for `ESP-Now` with `esp-idf` master

---

Cargo.toml
examples/http_request.rs
src/errors.rs
src/espnow.rs
src/eventloop.rs
src/handle.rs
src/http.rs
src/http/client.rs
src/http/server.rs
src/httpd.rs
src/lib.rs
src/log.rs
src/mdns.rs
src/mqtt.rs
src/mqtt/client.rs
src/netif.rs
src/nvs.rs
src/ota.rs
src/ping.rs
src/sntp.rs
src/systime.rs
src/timer.rs
src/tls.rs
src/wifi.rs
src/ws.rs
src/ws/client.rs

The crate documentation is quite _very_ sparse. It was often hard for me to piece together how to use a certain API.
Here's a first start:
- Add basic crate docs, especially for top-level modules
- Add usage example for HTTP client
Before:
After:
Note: I put the usage example in an example file instead of using rustdoc, because Rust currently does not support cross-compiled doctests.

Improve crate docs

---

src/ota.rs

The Rust wrapper for ```esp_ota_get_last_invalid_partition()``` is currently missing in ```esp-idf-svc```. This PR adds this function. This function is useful in the context of the two already implemented functions ```mark_running_slot_valid()``` and ```mark_running_slot_invalid_and_reboot()``` which are used to indicate that an app flashed through OTA is valid or not valid. The proposed new function ```get_last_invalid_slot()``` can be used during the OTA update process to check if the version of the new downloaded image is the same as the one which is stored in a slot which is marked as invalid.
The PR has been tested with a slot marked as invalid and with no invalid slots.

added Rust wrapper for IDF esp_ota_get_last_invalid_partition()

---

.github/workflows/ci.yml

With Xtensa toolchain release 1.5, defining GITHUB_TOKEN will increase our rate limit per hour.

Increase rate limit by adding secret

---

src/nvs.rs

This PR resolves #206. It contains a set of set / get functions for Rust primitive types to access NVS. With this PR ```esp-idf-svc``` is closer to the native IDF NVS functionality.
```get_str()``` is special, as it does not return a string, but a slice of u8. The reason is that it should be usable for heap/heapless scenarios. The conversion into the destination string type is left for the user of this function.

added nvs get/set for primitive types

---

src/wifi.rs

WIFI_EVENT_ROC_DONE specifically was missing and is used by esp_dpp. Causes a panic when calling esp_supp_dpp_start_listen();

Fix panic when using esp_dpp due to non-exhaustive WifiEvent match

---

Cargo.toml
src/log.rs

- log::EspLogger::set_target_level make function not method
Made this a function so that it can be called via log::EspLogger::set_target_level()
- log::EspLogger::should_log implement cache for CStrings
so it turns out that  esp-idf `function esp_log_level_get` builds a cache using the address
of the target and not doing a string compare.  This means we need to
build a cache of our own mapping the target string value to a consistant 
CString value.

make set_target_level() available and fix should_log() to use target not hard coded `rust-logging`

---

src/ws/client.rs

When receiving ping and pong messages on a websocket connection there would previously be an ```EspError``` returned to the user. This change adds the ping and pong events to the ```WebSocketEventType``` and returns them to the user.

Added websocket ping/pong event types

---

src/wifi.rs

[esp-idf added](https://github.com/espressif/esp-idf/commit/5c1ff3d7) the field `espnow_max_encrypt_num` to `wifi_init_config_t` which controls how many encrypted peers can be added.
If it's initialized to 0, none can be added.
C code would use the macro `WIFI_INIT_CONFIG_DEFAULT` to do the initialization, setting its value to `CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM` configured by the user.
This change does the same in Rust.

Set number of encrypted peers supported by espnow

---

src/wifi.rs

I recently became slightly frustrated with some of the documentation of the Wifi module. I noted that `WifiDriver` just calls functions from `esp_idf_sys` (which do have more detailed notes about their behaviour and preconditions), and also noted that `EspWifi`, `BlockingWifi` and `AsyncWifi` are just wrappers, adding links to the functions being wrapped.

Added docstrings for wifi module

---

examples/tls.rs
src/private/cstr.rs
src/tls.rs

I think this should be pretty much good as-is, these TODOs remain:
Let me know if this PR is headed into the right direction.

Abstraction for synchronous esp-tls

---

Cargo.toml
examples/nvs_get_set_c_style.rs
examples/nvs_get_set_raw_storage.rs

Please note that I have added a new dependence (postcard) just for the example. I don't know if that is OK for you or it is better to use something already added (json?).

Add NVS usage example using the native Rust API

---

Cargo.toml

Since uncased is only used in `http`, which itself depends on `alloc`, I thought another possibility could be to set `optional = true` on the `uncased` dependency, and only pull it when the `alloc` feature is raised. But this PR here is more straightforward.

Gate uncased alloc feature behind this alloc feature

---

src/http/client.rs

Set nevative value to `request_content_len` property if can't unwrap `content_len` somehow.
Ref: https://github.com/esp-rs/esp-idf-svc/issues/309
I want to implement streaming http post that sets `Transfer-Encoding: chunked` to the header and doesn't set `Content-Length`. But this library sets `Content-Length: 0` if I don't set `Content-Length` to the header and got 400 error (Please read above issue description).
As I investigate, I can avoid this behavior and can get what I'm looking for if set negative value to the second argument of  `esp_http_client_open` method.
https://github.com/esp-rs/esp-idf-svc/issues/309#issuecomment-1783754746
So I want to set negative value if can't fetch correct value from `content_len`.
Set `request_content_len` type to i64 because I want to set negative …

Set negative value to second argument of `esp_http_client_open` method if request header has `Transfer-Encoding: chunked`

---

src/ping.rs

The default TTL is 0, ie pinging any host that isn't on the local network will fail - with this, it succeeds

Set ping TTL to 64 (fixes #318)

---

src/mqtt/client.rs
src/tls.rs

Building against 0.47.3 with TLS PSK support enabled currently fails with
```
error[E0308]: mismatched types
--> /Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.47.3/src/tls.rs:58:19
|
58 |             hint: cstrs.as_ptr(conf.hint),
|                   ^^^^^^^^^^^^^^^^^^^^^^^ expected `*const i8`, found `Result<*const i8, EspError>`
|
= note: expected raw pointer `*const i8`
found enum `Result<*const i8, esp_idf_hal::sys::EspError>`
help: consider using `Result::expect` to unwrap the `Result<*const i8, esp_idf_hal::sys::EspError>` value, panicking if the value is a `Result::Err`
|
58 |             hint: cstrs.as_ptr(conf.hint).expect("REASON"),
|                                          +++++++++++++++++
For more information about this error, try `rustc …
```

Use fallible CString conversion for MQTT PSK too

---

src/http/server.rs
src/ws.rs

Documents some main functionality of the `httpd` module.
Not 100% complete, but it should be enough to users like me who want to program servers.

Docstrings for the httpd module

---

src/nvs.rs

The get_str function of nvs includes a 0 byte at the end that should not be there in rust.
I discovered this when passing the returned string to wifi setup and getting an esp error.

remove 0 byte from nvs.get_str

---

src/eventloop.rs

I'm implementing variable-sized events (via `serde`+`postcard`). The output of `postcard` is a `heapless::Vec<u8>`, which is exceedingly difficult to fit into a `[u32]`.
Since I cannot see any reason why the payload of a variable-sized event has to be alined to 4-byte words, I propose changing that to `[u8]`.
I have tested this change with https://gitlab.com/IvanSanchez/solanera/-/commit/94a974b70f47d75a6123580041fe0780a4b8e411 and everything seems to work allright.

Change payload of EspEventPostData from [u32] to [u8]

---

README.md
espflash.toml
partitions.csv

For running the examples we are using `cargo espflash`. By default `cargo espflash` will be using the partition.bin created inside esp-idf-sys ( `espflash` by default will use its own. The problem is that the default esp-idf-sys partition has only a 1MB big AppPartition size. All sdkconfig options for using different sized partitions only lead to a max AppPartition to 1.5MB and this is still to less for an wifi example with debug infos. So the simplest / cleanest solution is to simply provide one with the configuration file-

make cargo espflash work by adding a partition.csv

---

src/tls.rs

@ivmarkov Do you think something along those lines will work so we can also support accepted server clients?

Support for TLS server

---

src/nvs.rs

The partition name is wrapped in an option, in the case the option has a value, the pointer to the underlying value is not valid when calling esp_partition_find_first. By keeping the reference valid while calling C, it remains valid.
Fixes https://github.com/esp-rs/esp-idf-svc/issues/384

Fix: NVS encrypted partition name lookup

---

Cargo.toml
examples/http_client.rs
examples/http_ws_client.rs
examples/tls.rs
examples/wifi.rs
examples/wifi_async.rs
examples/wifi_async_send.rs
examples/wifi_static_ip.rs
examples/wps.rs
examples/wps_async.rs
src/wifi.rs

Reflect the changes to `ClientConfiguration` in `embedded-svc` which will be introduced by https://github.com/esp-rs/embedded-svc/pull/75.
Before marking it ready, https://github.com/esp-rs/embedded-svc/pull/75 has to be merged and the dependency to `embedded-svc` has to be changed back in `Cargo.toml`.

Reflect changes in embedded-svc wifi ClientConfiguration

---

src/ws/client.rs

Exposes crt_bundle_attach in EspWebSocketClientConfig too as it was already available for the http Configuration and MqttClientConfiguration.
Closes https://github.com/esp-rs/esp-idf-svc/issues/390

EspWebSocketClientConfig: expose crt_bundle_attach

---

src/ota.rs

When trying out the OTA functionality, my code was crashing when calling `get_boot_slot()` function. The function returns a Result, so crashing on error is rather counter-intuitive.
This PR adds graceful handling of calls `esp_ota_get_*_partition()` functions.

ota: handle partition errors gracefully

---

examples/http_client.rs

This PR will hopefully prevent [this](https://github.com/esp-rs/esp-idf-svc/issues/389) from happening again.
At first, I thought about creating a separate `https_client.rs`, but that would create a lot of duplicate code (also it'd look strange if `http_client.rs` had an HTTPS version and `http_server.rs` didn't). I feel the comment will get the message across with no code duplication.
Note: There's aliasing here: 
use esp_idf_svc::http::client::{Configuration as HttpConfiguration, EspHttpConnection};
To prevent conflict with this:
```
use embedded_svc::{
// More imports
wifi::{AuthMethod, ClientConfiguration, Configuration},
};
```

Add comment with HTTPS example

---

src/wifi.rs

This PR exposes the [wifi_event_ap_staconnected_t](https://docs.espressif.com/projects/esp-idf/en/v4.3.7/esp32/api-reference/network/esp_wifi.html#_CPPv428wifi_event_ap_staconnected_t)  and [wifi_event_ap_stadisconnected_t](https://docs.espressif.com/projects/esp-idf/en/v4.3.7/esp32/api-reference/network/esp_wifi.html#_CPPv431wifi_event_ap_stadisconnected_t) structs for the WifiEvents `ApStaConnected` and `ApStaDisconnected` respectively.
I tested it so far with an ESP-WROOM-32 development board.

Exposes WifiEvent#ApStaConnected and WifiEvent#ApStaDisconnected event info

---

src/http/client.rs

Fixes #399.
I tested by using a loop that sends many HTTPS requests and by removing the part that reads and drains the data in the `http_client.rs` example. The pattern was the same: `ESP_FAIL` without `flush_response()`. No `ESP_FAIL` with `flush_response()`.
Some considerations:
1. Will flushing the response data in `initiate_request()` cause issues that cannot be observed in the `http_client.rs` example?
2. If the response data is [flushed](https://github.com/weiying-chen/esp-idf-svc/blob/feature/flush-response/src/http/client.rs#L213) in `initiate_request()`, will [flushing](https://github.com/weiying-chen/esp-idf-svc/blob/feature/flush-response/src/http/client.rs#L452) the response data in `fetch_headers()` be redundant?

Flush responses to avoid repeated request failures

---

src/eth.rs
src/wifi.rs

Related: #401 
I think it would make sense for the *Driver callbacks to use owned parameters rather than references (slices). This way they can be e.g. sent via `mpsc::channel` without another allocation, e.g. `to_vec()`.
I'm not the most experienced with Rust so I'm very open to feedback and further guidance.

Owned network callback parameters

---

src/eth.rs

This looks like an oversight.
Too bad the C bindings aren't `#[must_use]` :sweat_smile: .

Fix missing error return

---

src/eventloop.rs
src/wifi.rs

As requested. The lint is currently only in nightly clippy.

clippy: Add type annotations to `transmute` calls

---

src/ping.rs

This change allows disabling IPv6 - the type is defined as a union only when IPv4 and IPv6 are enabled [here](https://github.com/espressif/esp-lwip/blob/a45be9e438f6cf9c54ec150581819c3b95d5af6b/src/include/lwip/ip_addr.h#L69)
I'm not sure if it should be patched in this repo, or at bindgen time, let me know

Allow disabling IPv6

---

examples/wifi_static_ip.rs
src/netif.rs
src/wifi.rs

I think `wrap_all` itself should be gated by the `cfg` but wasn't sure if it was desirable or not

Support disabling SoftAP

---

src/http/server.rs

Hi!
I am making an IP camera using an ESP32CAM, and I need to have 2 HTTP servers. The first one handles most of the requests (like index...) but then I need a second one which only handles the `/stream` which is going to have a `loop` inside that continuously sends the images to the HTTP client (check this: https://stackoverflow.com/questions/47729941/mjpeg-over-http-specification).
If I only have 1 server as soon as I receive a `/stream` request everything is blocked (because of the `loop`).
The problem now is that since `ctrl_port` is hidden from Rust, I can't start a second server since the `ctrl_port` is already occupied by the first one.

Exposes ctrl_port in the configuration of an HttpServer

---

src/private/cstr.rs
src/wifi.rs

Fixes #337
Also fixes the conversion of ssid/password in the config to no longer assume 0 termination - this lead to problems when routers send a 64 byte access token to us instead of a password

Fix WPS regression and cred conversion

---

src/tls.rs

The additional handshake info is returned by the negotiate() methods. Doing it this way should incur no space overhead for users that simply discard the return value.

Support extracting the protocol chosen with ALPN.

---

src/tls.rs

This is required, for example, by the Hyper HTTP2 client implementation.

Make EspTls and EspAsyncTls Send when possible

---

src/http/server.rs

This commit addresses an issue where the EspHttpServer does not handle errors correctly, causing the HTTP connection to hang indefinitely. When an error is returned from a closure handling an HTTP request, the server logs the error but does not complete the response. As a result, the client hangs indefinitely, waiting for the response to be fully sent. This PR adds a call to `connection.complete()` in the error handling code to ensure that the response is properly finalized.
Fixes: https://github.com/esp-rs/esp-idf-svc/issues/328

Fix: Properly complete HTTP response on error

---

src/private/mutex.rs
src/tls.rs

I had to take the RefCell out, because wait() would await holding &RefCell, making the futures require Sync.
It was replaced by a Mutex, since the socket read/write splitting design is not clear yet.

Allow TLS negotiation on a multi-threaded executor.

---

CHANGELOG.md
src/http/server.rs

This PR "operates" the HTTP server wrapper in a similar way how all other APIs accepting callbacks were altered during the previous release cycle: 
- All APIs which used to take non-static callbacks, now only accept `'static` ones, which is safe
- All of them now also have a mirror `_nonstatic` APIs marked with `unsafe` which continue to accept non-`'static` callbacks, but have big fat `#Safety` strings attached
With this PR, what would happen to the code that was posted in Matrix by a user, is that the code would stop compiling, because the handlers are non-static in that they borrow a ref to a `Mutex` which lives on the stack (and the program crashes because additionally it calls `core::mem::forget` on a value that continues to live after the stack had gone).

Mark all non-static handlers as unsafe

---

examples/http_ws_server_page.html

Instead of using a fixed URL, base the ws url based off of the current http URL. This will make it easier to modify the examples, such as connecting to an existing Wi-Fi network instead of creating one.

Use ws url based on current page's url

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
src/bt.rs

Subject says it all.
BT controller initialization for these chips is different from the currently supported esp32/esp32c3/esp32s3.

Support for esp32c2, esp32h2, esp32c6 and in future esp32h4 and esp32c5

---

src/eth.rs

Add the option to use a polling strategy instead of a interrupt pin for the SPI EthDriver.
The old api was left intact, while a new `EthDriver::new_spi_with_event_source` was added.

feat(eth): Implement alternative polling mode

---

src/wifi.rs

I am using the is_scan_done function to check if I can start a new scan. I noticed this problem when I switched from using get_scan_result_n() to get_scan_result(). The state behavior should at least be matched.

get_scan_result version stomps the scan state from Done to Idle.

---

src/log.rs

I'm relatively sure `set_target_level` is not currently defined correctly.
This PR fixes this. That is, until / if we decide to de-couple the Rust logging from the ESP IDF logging, which is possible since > 2 years. I.e. since [these changes landed](https://github.com/esp-rs/esp-idf-svc/commit/6e24987f217fbc951161d7caf19ae9841e70b036).

Fix set_target_level

---

src/private/unblocker.rs
src/private/zerocopy.rs

There were already some Send implementations.
However, they weren't completely correct, which made it impossible to use the async mqtt client in e.g. a tokio worker thread.
Note that it could be used in the async main task, because that never sends off any work to other worker threads, and thus Send is not required. The errors would surface when trying to use tokio::spawn with an async mqtt client.
See also https://users.rust-lang.org/t/implementation-of-send-is-not-general-enough-but-cannot-make-it-more-general/115087
Also. I note that the Unblocker deletes the FreeRTOS task when it is dropped. This seems sketchy. Deleting the task will, if I understand correctly, cause it to stop running immediately, without running any associated `Drop` implementations. Couldn't this cause memory …

Make async mqtt client implement Send

---

src/mqtt/client.rs

This will allow users to use the `EspMqttClient::new_cb` method together with the async mqtt client, if one should so desire. For example, if one wants to use a different event channel.

Make EspAsyncMqttClient::wrap public.

---

src/mqtt/client.rs

Forgot this one in the previous PR.
Without it, I can get errors like this:
```rust
error[E0277]: `*mut esp_mqtt_error_codes` cannot be shared between threads safely
--> /home/arong/projects/embedded/mqtt_sync/src/lib.rs:156:9
|
156   | /         tokio::spawn(async move {
157   | |             Self::start(client, connection, queue_receiver, storage2)
158   | |                 .await
159   | |                 .unwrap()
160   | |         });
| |__________^ `*mut esp_mqtt_error_codes` cannot be shared between threads safely
|
= help: within `EspMqttEvent<'_>`, the trait `Sync` is not implemented for `*mut esp_mqtt_error_codes`, which is required by `{async block@/home/arong/projects/embedded/mqtt_sync/src/lib.rs:156:22: 160:10}: Send`
note: required because it appears within the type …
```

Implement Sync for EspMqttEvent.

---

src/eventloop.rs

Applies an event source filter to asynchronously subscribed events. Previously async subscriptions would attempt to deserialize all events in the event loop with the specified deserializer.
Fixes (suspected) #383 for me.
There's probably a better way to implement the event filter so that it gets applied in the event loop thread before channeling the events all the way to the async thread, but this is what I came up with as a quick fix.
Feel free to close the PR and implement a better approach. :)

Filter asynchronous events

---

examples/http_client.rs

#404 renders this code unnecessary:
```
// Drain the remaining response bytes
while response.read(&mut buf)? > 0 {}
```
Note: I tested on my machine. The [http_client.rs](https://github.com/esp-rs/esp-idf-svc/blob/master/examples/http_client.rs) example still runs successfully.

Remove unnecessary buffer draining in HTTP client example

---

src/wifi.rs

I have added the function `esp_wifi_sta_get_rssi` in the Wifi trait. Nothing fancy and works well when connected. I can rename the function if that works better.

Added esp_wifi_sta_get_rssi function in EspWifi

---

examples/nvs_get_set_raw_storage.rs

Fix incorrect key variable being logged for the struct storage for raw NVS access example

Fix NVS example logging incorrect variable

---

src/mqtt/client.rs

Exposes `esp_mqtt_client_set_uri` in both blocking and async clients.
Fixes #481 by moving unsafe { core::ffi::CStr::from_bytes_with_nul_unchecked(&work.topic) } into  their respective commands. I'm not sure why this works.
Doesn't fix #419. I'm also not sure why the original code works on xtensa but not riscv.

Expose esp_mqtt_client_set_uri. Fix issue #481.

---

src/eth.rs

Fix for this error:
```
Compiling esp-idf-svc v0.49.1 (esp-idf-svc)
error[E0560]: struct `esp_idf_hal::sys::eth_esp32_emac_config_t` has no field named `smi_mdc_gpio_num`
--> esp-idf-svc/src/eth.rs:445:13
|
445 |             smi_mdc_gpio_num: mdc,
|             ^^^^^^^^^^^^^^^^ `esp_idf_hal::sys::eth_esp32_emac_config_t` does not have this field
|
= note: available fields are: `__bindgen_anon_1`, `clock_config`, `dma_burst_len`, `intr_priority`
error[E0560]: struct `esp_idf_hal::sys::eth_esp32_emac_config_t` has no field named `smi_mdio_gpio_num`
--> esp-idf-svc/src/eth.rs:446:13
|
446 |             smi_mdio_gpio_num: mdio,
|             ^^^^^^^^^^^^^^^^^ `esp_idf_hal::sys::eth_esp32_emac_config_t` does not have this field
|
= note: available fields are: `__bindgen_anon_1`, …
```

Fix for ESP-IDF 5.3

---

src/log.rs

This change allows to set one of these configurations
- CONFIG_LOG_TIMESTAMP_SOURCE_RTOS
- CONFIG_LOG_TIMESTAMP_SOURCE_SYSTEM 
source: https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig.html#config-log-timestamp-source
I'm open for suggestions on how to properly structure this as I'm not sure how to do this kind of conditional selection of what to print as the original timestamp is u32 and I wanted to avoid having another nested case distinction inside both color paths.
This allows timestamps like the following if CONFIG_LOG_TIMESTAMP_SOURCE_SYSTEM is set
```
I (00:00:01.742) main_task: Calling app_main()
```

enable logging with milliseconds since boot and system time in rust logs depending on configuration

---

src/log.rs

In #494 an issue with an incorrect configuration attribute was introduced and the regular CONFIG_LOG_TIMESTAMP_SOURCE_RTOS option is not usable anymore. This is a fix for this bug

Fix incorrect logging configuration attribute introduced in #494

---

src/ota.rs

I've been recently implementing OTA for my project and noticed the documentation was lacking. I decided to add documentation to improve my own understanding and hopefully make it more accessible to others.
I used [ESP-IDF OTA documentation](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/ota.html) for reference.
As I'm not an expert here, I would appreciate if someone could check the correctness, especially the module doc.
Additionally, I'm not sure about the contents of `EspOtaUpdate::flush()`. On one hand, this function does nothing and the user may want to know about it, on the other hand, I just exposed implementation details. Should the documentation be written with the assumption that this function does something? This would encourage users to use it …

Document OTA API

---

src/netif.rs

According to this issue, https://github.com/espressif/esp-idf/issues/10359
The default name for an ethernet netif is `ETH_DEF`, but it is hardcoded as `ETH_CL_DEF`. The mDNS service attempts to look up the netif based on the name during initialisation, but it won't find it unless the user wraps their own netif with the new name.

Change default eth key

---

examples/http_ws_server.rs

a (supposed) C string was treated/decoded as Rust string. This works okay-ish, but leads to a trailing null byte (valid in UTF-8!) which e.g. `serde_json` doesn't like.

examples/http_ws_server.rs: fix string decoding

---

src/log.rs

Fixes #520 where no newlines were printed if `CONFIG_LOG_COLORS=n` as the newline was only printed if `color.is_some()`.
Now the `writeln!()` call is at the end and is always called.

Fix missing newline if CONFIG_LOG_COLORS=n is set

---

Cargo.toml
src/mdns.rs

Hello,
This is a very ugly hack so you most likely do not want to merge this as is, i'm open to working on any modifications.
The point of the commit is that currently, if ipv6 is disabled in sdkconfig and mdns is imported as an external component in Cargo.toml, the project does not compile because the C functions called by mdns.rs aren't exposed anymore.
Is there a better way to do this? In the meantime, this worked for me.

gatekeep mdns ipv6 behind feature flag

---

src/timer.rs

Currently the esp timer service hardcodes the `skip_unhandled_events` flag to `false` which means there is no way to construct a timer that doesn't wake the device from light sleep.
This change introduces a `skip_unhandled_events` fn on the `EspTimerService` which allows changing the value of this timer flag.
---
I added this as a mutating fn on the timer service - but I wonder if it's a better design to make the `new` constructor accept this flag. I didn't want to change it's signature though to avoid introducing a breaking change.

Allow setting skip_unhandled_events on esp timer

---

src/eth.rs

Currently, on my end, increasing log verbosity beyond info with ethernet enabled crashes with a stack overflow in the emac_rx task. This simply increases the stack size of the task to prevent the crash.
Additionally, this reflects [the default for the esp-idf project](https://github.com/espressif/esp-idf/blob/master/components/esp_eth/include/esp_eth_mac.h#L374C1-L375C1).
Unless i'm mistaken there is no kconfig setting that can be set to move this value.
Tested on my end with log set to debug level, crashes don't occur anymore.

Increase emac_rx stack size

---

CHANGELOG.md
src/eth.rs
src/wifi.rs

Second part of #246, adds wrappers for `esp_wifi_get_promiscuous` and `esp_wifi_set_promiscuous`.
If I find the time I'll make wrappers for those three functions in the todo, though for now this fixes #246.
Minimal repo, it works.

Safe wrappers for wifi promiscuous

---

CHANGELOG.md
src/io.rs

- [v] I have updated existing examples or added new ones (if applicable).
- [v] I have used `cargo fmt` command to ensure that all changed code is formatted correctly.
- [v] I have used `cargo clippy` command to ensure that all changed code passes latest Clippy nightly lints.
- [v] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-idf-svc/blob/main/esp-idf-svc/CHANGELOG.md) in the **_proper_** section.
A new type, `esp_idf_svc::io::vfs::BlockingStdIo` that allows the user to switch to buffered and blocking IO for the Rust `std::io::stdout`, `std::io::stderr` and most importantly, `std::io::stdin`, …

Blocking and buffered StdIo

---

CHANGELOG.md
src/http/server.rs

My attempt at #538. It works flawlessly on my end. 
```rust
http_server.fn_handler("/", Method::Get, {
move |mut request| {
let html = "hello world";
let connection = request.connection();
log::info!("SOURCE IP: {}", connection.raw_connection()?.source_ip()?);
connection.initiate_response(200, Some("OK"), &[("Content-Type", "text/html")])?;
connection.write(html.as_bytes())?;
Ok::<(), Error>(())
}
})?;
```
```
I (00:00:10.545) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.100.2
I (00:00:12.947) charizhard::http: SOURCE IP: 192.168.100.2
```
fixes #538

Add source_ipv4, source_ipv6 functions in EspHttpRawConnection

---

CHANGELOG.md
src/eth.rs
src/wifi.rs

When NimBLE is enabled, the following error occurs.
```
error[E0433]: failed to resolve: `log` is a struct, not a module
--> /home/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.50.0/src/eth.rs:1050:13
|
1050 |             log::info!("Driver set in promiscuous mode");
|             ^^^ `log` is a struct, not a module
error[E0433]: failed to resolve: `log` is a struct, not a module
--> /home/a/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.50.0/src/eth.rs:1052:13
|
1052 |             log::info!("Driver set in non-promiscuous mode");
|             ^^^ `log` is a struct, not a module …
```

Fix ambiguous name error

---

.github/configs/sdkconfig.defaults
CHANGELOG.md
Cargo.toml
src/timer.rs

- [v] I have updated existing examples or added new ones (if applicable).
- [v] I have used `cargo fmt` command to ensure that all changed code is formatted correctly.
- [v] I have used `cargo clippy` command to ensure that all changed code passes latest Clippy nightly lints.
- [v] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-idf-svc/blob/main/esp-idf-svc/CHANGELOG.md) in the **_proper_** section.
An `embassy-time-driver` implementation compatible with the just-released backwards-incompatible `embassy-time-driver` V0.2.
With a custom example that unfortunately cannot be pushed, or else `esp-idf-svc` …

embassy-time-driver V0.2 impl

---

CHANGELOG.md
Cargo.toml

The `embedded-svc` crate have a `use_serde` feature, which is not enabled by default. To enable it, it have to be propagated from this crate.
This feature is handy when dealing with configuration. In my use case, I use it to parse to have a simple json file for my wifi configuration.
It's a simple cargo feature flag.

Expose `embedded-svc/use_serde` feature

---

examples/ota_http_client.rs
src/ota.rs

The documentation around OTA is very limited, and you have to make a lot of research on your own.
This PR introduces the example I would have been happy to find when implementing OTA updates on my project :-)
I've copy pasted the code from my working project. Not sure if there are unit tests for examples in this repo ?
I haven't added a changelog entry, not sure the addition of an example is actually a change :-P

Add example of OTA update using http client

---

CHANGELOG.md
src/mqtt/client.rs

This change implements get_outbox_size() on the EspMqttClient to retrieve the amount of bytes currently stored in the MQTT outbox.
Additionally implement a configurable option in MqttClientConfiguration to limit the outbox size to the given amount of bytes so there is no ever growing outbox size that might fill up the entire RAM.
I tested the limit with this configuration and sent a a lot of bytes
```
&MqttClientConfiguration {
client_id: Some(client_id),
username,
password,
outbox_limit: Some(5000),
..Default::default()
},
```
and tested it with
```
if client.get_outbox_size() > 5100 {
error!("too much in the outbox, ignore this …
```

Implement MQTT outbox limits and get_outbox_size()

---

CHANGELOG.md
src/ota.rs

The OTA process requires first erasing data in the flash partition and then writing the new image. By default the entire image is erased, even though we only need to erase enough space to fit the image. For esp32s with large flash sizes and relatively small images, the erasing can dominate total OTA time.
This PR adds an `initiate_update_with_known_size` variant to allow passing through the size parameter to the underlying ESP IDF library rather than the default `OTA_SIZE_UNKNOWN`.
I tested by using by specifying the size when performing an OTA. For me, this sped up the erase portion of OTA by 3x. (esp32s3 with 32M flash, two 8M …

Allow specifying known flash size during OTA to make erasing faster

---

CHANGELOG.md
examples/http_ws_server.rs
src/http/server.rs

Added argument `subprotocol_list` to `EspHttpServer::ws_handler` to allow subprotocols to be supported by server-side WebSockets.
Websockets in reality often rely on subprotocols (Sec-WebSocket-Protocol). The underlying C code supports WebSocket subprotocols, but the Rust layer obviously does not. This PR exposes the attribute `supported_subprotocol´ of the struct `http_ui` to the handler. The added argument is an optional, comma-separated list of sub-protocols. The attribute is only updated, if the supplied Option is not None.
I tested against a custom client that requires the use of a subprotocol. The tests have been carried …

Exposes WS subprotocol in EspHttpServer::ws_handler()

---

CHANGELOG.md
src/nvs.rs

- [-] I have updated existing examples or added new ones (if applicable). 
- No examples affected
Some functions in the NVS interface were left mutable which forced the use of a second mutex from rust. To avoid the need for double locking i removed mutability from these functions. This solution is viable because the C interface is already protected by mutexes and locking from rust should not be necessary. (The majority of the setters are non-mutable currently)
The C lock is visible here: https://github.com/espressif/esp-idf/blob/master/components/nvs_flash/src/nvs_api.cpp#L421
- I double checked that all the affected functions are indeed protected on the C side.
- The functions are working without a mutex from rust.

Fixed inconsistent mutability in NVS

---

src/io.rs

This a minor patch to fix broken compilation under some conditions.
`crate::fs` is only compiled when the `experimental` feature is enabled, but the user may have started using the `joltwallet/littlefs` component through its raw bindings, without relying on `experimental`.
But `esp_idf_comp_joltwallet__littlefs_enabled` would be true, causing `MountedLittlefs` to be compiled even when `crate::fs` isn't. `crate::fs::littlefs::PartitionRawData` can't be unresolved and breaks the build.
I'm using a local repo of esp-idf-svc as a path dependency.

Compile MountedLittlefs only if experimental is enabled

---

CHANGELOG.md
examples/bt_ble_gap_scanner.rs
src/bt/ble/gap.rs

Add functions to start and stop ble scanning. These functions are required to detect nearby ble devices.
I executed the added example on a esp32c3.

Add functions to start and stop ble scanning

---

CHANGELOG.md
examples/mdns_advertise.rs

Adds simple example showing how to advertise a service using mDNS. I thought this would be useful to new users of the crate, especially considering the included comment telling users about the mDNS component on ESP IDF >= 5.
Ran the example on an AI-Thinker ESP32-CAM and used the following command to verify the service is advertised correctly:
```bash
sudo avahi-daemon --kill && avahi-browse -a -t --resolve --no-db-lookup
```

add mDNS advertise example

---

CHANGELOG.md
src/nvs.rs

This PR adds support for:
I guess this was forgotten? It is nice to have when calling `esp-idf-sys` functions.
I use a library that stores some data in the `EspNvs`, and I want to empty all stored data in some circumstances. Previously there wasn't any functionality to accomplish that, which is why I made this PR.
This function allows iterating over all stored keys. I don't need this function, but #340 requests this function and the `erase_all`, so I added it to close that issue with this PR
Regarding the implementation: It seems to work, but I don't know how the API should look like, couldn't find many references.
The main …

Implement `clear` and `iter` functionality for `EspNvs`
