esp-rs/esp-idf-svc

src/nvs_storage.rs
Solving some issues with pointers for the in/out buffers to esp-idf.
Also settles solely on 'blobs' and uses none of the other datatypes
of esp idf nvs storage.
I did some debugging on how to make nvs storage work on the ESP32 -- and this is what I came up with; most importantly it seemed that the data buffers were not correctly transferred to esp idf in the nvs_get_* and nvs_set_* functions. Furthermore it seems like the esp idf nvs storage functions do not allow to mix datatypes, i.e. doing an 'nvs_get_u64' on a piece of data that is stored as a blob does not given 'incorrect length' as error, but rather 'not found' -- thus some logic was not working.
This implementation settles on blobs and uses nothing else; while blob support is sufficient and very desirable in that it forces …
=> Making put_raw and get_raw work

src/eth.rs, src/netif.rs, src/wifi.rs
This pull request depends on: https://github.com/esp-rs/embedded-svc/pull/3
=> added an option to set hostname in STA mode

src/mqtt/client.rs
construct mqtt topic string from (ptr,len) instead of assume null-terminated
=> fix trailing garbage in mqtt topic string

src/http/client.rs
exposing these tls options enabled me to get https _with_ server verification working like so
```rs
let mut client = EspHttpClient::new(&EspHttpClientConfiguration {
use_global_ca_store: true,
crt_bundle_attach: Some(esp_idf_sys::esp_crt_bundle_attach),
..Default::default()
})?;
```
=> [http/client] expose basic tls config

src/http/server.rs
I left the TODO note about lowercasing because I haven't benchmarked any of this.
Tested briefly on an ESP32-C3.
=> Also use uncased for experimental HTTP server header names

src/eth.rs
~~Needs marker trait: https://github.com/esp-rs/esp-idf-hal/pull/56~~
=> Make Clock configurable

src/eth.rs, src/mdns.rs, src/wifi.rs
Compilation errors occurred when compiling with no-std, so I fixed it.
=> Fix no-std compilation

Cargo.toml, src/espnow.rs, src/eth.rs, src/eventloop.rs, src/http/client.rs, src/http/server.rs, src/httpd.rs, src/mdns.rs, src/mqtt/client.rs, src/netif.rs, src/notify.rs, src/nvs.rs, src/ota.rs, src/ping.rs, src/private/cstr.rs, src/private/stubs.rs, src/timer.rs, src/tls.rs, src/wifi.rs, src/ws/client.rs
- Requires esp-rs/esp-idf-sys#157
=> Adjust for `esp-idf-sys` size_t -> usize

.github/workflows/publish.yml, Cargo.toml
Also fixed a bug where embassy-sync feature was not enabled in the hal when using the `embassy-time-isr-queue` feature.
=> Show docs for all features

src/wifi.rs
=> fix conditional checks

src/ota.rs
=> Fix for issue #204 wrong FirmwareInfo

src/sntp.rs
This has been tested on a vanilla ESP32.
=> Add wrapper to specify callback for SNTP

src/ota.rs
This commit adds the `EspOta.get_update()` function to improve the ergonomics of implementing OTA update logic.
The reasoning behind this, that the current approach requires holding a mutable reference to EspOtaUpdate whilste holding a the reference to EspOta, which is tricky when working with message handling event loops.
Our use-case is as follows.
We implemented OTA via Bluetooth in a way that allows background updates while continuing normal operation.
Previously, our approach worked fine, as `EspOta<Update>` was returned as a owned struct.
This allowed us to do something like this:
```rs
let mut ota: EspOta = EspOta::new().unwrap();
let mut ota_update: Option<EspOta<Update>> = None;
let mut ota_bytes_written = 0;
loop {
match rx.recv() {
Ok(message) => {
handle_message(
message,
&mut …
```
=> Add EspOta.get_update()

.github/workflows/ci.yml, .github/workflows/publish-dry-run.yml, .github/workflows/publish.yml
- Remove `libncurses5` installation
- Update `actions/checkout` version
- Replace `actions-rs/toolchain` by `dtolnay/rust-toolchain`
- Merge `Std` and `Default to nightly` steps into `dtolnay/rust-toolchain`
=> Improve CI

src/wifi.rs
Added some doc and examples, to clarify the use of the WiFi scan API to avoid #213.
=> Add docs for wifi scan

src/eth.rs
This should allow to share ETH with other devices on the same SPI bus
=> Use SpiDriver to setup ETH

src/http/client.rs
See issue for further information.
https://github.com/esp-rs/esp-idf-svc/issues/235#issuecomment-1463590779
=> Improve error handling in EspHttpConnection::read (Issue #235)

src/private/cstr.rs, src/wifi.rs
Aims to fix https://github.com/esp-rs/esp-idf-svc/issues/291, but probably requires more polishing
=> Filter out bad wifi APs when scanning

src/nvs.rs
This patch implements the encryption API. It may still need some work, like putting stuff behind compiler options (I think if your sdkconfig does not contain the encryption parameters, it will fail compilation). Also, there is quite a lot of duplication, which feels wrong, but I both want to learn what is a good way to prevent it and I want to improve the code.
In order to run it, (ok, as I am writing this, it feels like I should add documentation as well...), build your app with the following keys in your defconfig:
```
CONFIG_SECURE_FLASH_ENC_ENABLED=y
CONFIG_SECURE_FLASH_ENCRYPTION_MODE_DEVELOPMENT=y
CONFIG_SECURE_FLASH_HAS_WRITE_PROTECTION_CACHE=y
CONFIG_SECURE_FLASH_UART_BOOTLOADER_ALLOW_ENC=y
CONFIG_SECURE_FLASH_SKIP_WRITE_PROTECTION_CACHE=y
CONFIG_SECURE_FLASH_CHECK_ENC_EN_IN_APP=y …
```
=> Added Esp nvs ecryption

src/ota.rs
This is required to free the resources allocated by `esp_ota_begin`.
=> Implement Drop for EspOtaUpdate

src/wifi.rs
related https://github.com/esp-rs/embedded-svc/pull/65
=> Issue 333 panic when scanning wifi with unknown auth method

src/mqtt/client.rs
=> Add Drop implementation for EspMqttClient

src/fs/config.rs, src/sd/host.rs
=> Fix esp-idf >= v5.3beta

src/mqtt/client.rs, src/private/unblocker.rs, src/private/zerocopy.rs
- Improve docs for mqtt/client
- Improve docs for private/zerocopy
- Avoid potential memory leak when dropping mqtt clients
=> Avoid potential memory leak when dropping mqtt clients

src/espnow.rs
Currently the espnow bindings for `register_recv_cb` only give a handle on the src_addr from the sending peer. This makes it impossible to determine if the frame was sent on the BROADCAST address.
This change updates the first argument to the receive cb to accept a new `ReceiveInfo` struct containing `src_addr` and `dst_addr`.
This allows writing code along the lines of:
```rust
controller.register_recv_cb(|info, data| {
if info.dst_addr == &espnow::BROADCAST {
log::info!("Received broadcast!");
return;
}
// do something else with 'normal' packet.
})?;
```
=> Expose src_addr and des_addr in espnow recv cb

src/nvs.rs
Adds documentation for some of the methods in `EspNvs`.
=> Document `str_len` and `blob_len` methods in `EspNvs`.
